common:
  log: # 日志打印配置
    level: "debug" # 日志等级，推荐：debug、info、warn 其他可选：error、fatal、panic
    out: "/dev/stdout" # 输出方式，推荐：/dev/stdout 可选：/dev/stderr
    format: "text" # 日志打印格式，可选：
    logPath: "./logger" # 日志文件存储目录
    maxAge: 604800 # 文件最大保存时间(s)
    rotationTime: 86400 # 日志切割时间间隔(s)
    logSize: 1024 # 日志文件大小(M)
    reportCaller: true # 是否打印文件行号
  db: # 数据库配置(mysql)，mysql服务部署 见部署手册，或基于TDSQL/CDB搭建
    username: "root" # 数据库用户名
    password: "XXXX" # 数据库密码
    host: "127.0.0.1:3306" # 数据库连接地址
    database: "megooo" # 数据库名
    debug: true
    maxOpenConn: 50  # 连接池最大连接数
    maxIdleConn: 2   # 最大空闲连接
    maxLifetime: 30   # 空闲连接的超时时间